//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.8
//
// <auto-generated>
//
// Generated from file `EventDataModule.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include "include/EventDataModule.h"
#include <IceUtil/PushDisableWarnings.h>
#include <Ice/LocalException.h>
#include <Ice/ValueFactory.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/InputStream.h>
#include <Ice/OutputStream.h>
#include <IceUtil/PopDisableWarnings.h>

#if defined(_MSC_VER)
#pragma warning(disable : 4458) // declaration of ... hides class member
#elif defined(__clang__)
#pragma clang diagnostic ignored "-Wshadow"
#elif defined(__GNUC__)
#pragma GCC diagnostic ignored "-Wshadow"
#endif

#ifndef ICE_IGNORE_VERSION
#if ICE_INT_VERSION / 100 != 307
#error Ice version mismatch!
#endif
#if ICE_INT_VERSION % 100 >= 50
#error Beta header file detected
#endif
#if ICE_INT_VERSION % 100 < 8
#error Ice patch level mismatch!
#endif
#endif

#ifdef ICE_CPP11_MAPPING // C++11 mapping

namespace
{

    const ::std::string iceC_EventDataModule_EventsDataInterface_ids[2] =
        {
            "::EventDataModule::EventsDataInterface",
            "::Ice::Object"};
    const ::std::string iceC_EventDataModule_EventsDataInterface_ops[] =
        {
            "ice_id",
            "ice_ids",
            "ice_isA",
            "ice_ping",
            "registerEvent"};
    const ::std::string iceC_EventDataModule_EventsDataInterface_registerEvent_name = "registerEvent";

}

bool EventDataModule::EventsDataInterface::ice_isA(::std::string s, const ::Ice::Current &) const
{
    return ::std::binary_search(iceC_EventDataModule_EventsDataInterface_ids, iceC_EventDataModule_EventsDataInterface_ids + 2, s);
}

::std::vector<::std::string>
EventDataModule::EventsDataInterface::ice_ids(const ::Ice::Current &) const
{
    return ::std::vector<::std::string>(&iceC_EventDataModule_EventsDataInterface_ids[0], &iceC_EventDataModule_EventsDataInterface_ids[2]);
}

::std::string
EventDataModule::EventsDataInterface::ice_id(const ::Ice::Current &) const
{
    return ice_staticId();
}

const ::std::string &
EventDataModule::EventsDataInterface::ice_staticId()
{
    static const ::std::string typeId = "::EventDataModule::EventsDataInterface";
    return typeId;
}

/// \cond INTERNAL
bool EventDataModule::EventsDataInterface::_iceD_registerEvent(::IceInternal::Incoming &inS, const ::Ice::Current &current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    StructRegisterEvent iceP_structRegisterEvent;
    istr->readAll(iceP_structRegisterEvent);
    inS.endReadParams();
    this->registerEvent(::std::move(iceP_structRegisterEvent), current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool EventDataModule::EventsDataInterface::_iceDispatch(::IceInternal::Incoming &in, const ::Ice::Current &current)
{
    ::std::pair<const ::std::string *, const ::std::string *> r = ::std::equal_range(iceC_EventDataModule_EventsDataInterface_ops, iceC_EventDataModule_EventsDataInterface_ops + 5, current.operation);
    if (r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch (r.first - iceC_EventDataModule_EventsDataInterface_ops)
    {
    case 0:
    {
        return _iceD_ice_id(in, current);
    }
    case 1:
    {
        return _iceD_ice_ids(in, current);
    }
    case 2:
    {
        return _iceD_ice_isA(in, current);
    }
    case 3:
    {
        return _iceD_ice_ping(in, current);
    }
    case 4:
    {
        return _iceD_registerEvent(in, current);
    }
    default:
    {
        assert(false);
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }
    }
}
/// \endcond

/// \cond INTERNAL
void EventDataModule::EventsDataInterfacePrx::_iceI_registerEvent(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>> &outAsync, const StructRegisterEvent &iceP_structRegisterEvent, const ::Ice::Context &context)
{
    outAsync->invoke(
        iceC_EventDataModule_EventsDataInterface_registerEvent_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream *ostr)
        {
            ostr->writeAll(iceP_structRegisterEvent);
        },
        nullptr);
}
/// \endcond

/// \cond INTERNAL
::std::shared_ptr<::Ice::ObjectPrx>
EventDataModule::EventsDataInterfacePrx::_newInstance() const
{
    return ::IceInternal::createProxy<EventsDataInterfacePrx>();
}
/// \endcond

const ::std::string &
EventDataModule::EventsDataInterfacePrx::ice_staticId()
{
    return EventsDataInterface::ice_staticId();
}

namespace Ice
{
}

#else // C++98 mapping

namespace
{

    const ::std::string iceC_EventDataModule_EventsDataInterface_registerEvent_name = "registerEvent";

}

/// \cond INTERNAL
::IceProxy::Ice::Object * ::IceProxy::EventDataModule::upCast(EventsDataInterface *p) { return p; }

void ::IceProxy::EventDataModule::_readProxy(::Ice::InputStream *istr, ::IceInternal::ProxyHandle<EventsDataInterface> &v)
{
    ::Ice::ObjectPrx proxy;
    istr->read(proxy);
    if (!proxy)
    {
        v = 0;
    }
    else
    {
        v = new EventsDataInterface;
        v->_copyFrom(proxy);
    }
}
/// \endcond

::Ice::AsyncResultPtr
IceProxy::EventDataModule::EventsDataInterface::_iceI_begin_registerEvent(const ::EventDataModule::StructRegisterEvent &iceP_structRegisterEvent, const ::Ice::Context &context, const ::IceInternal::CallbackBasePtr &del, const ::Ice::LocalObjectPtr &cookie, bool sync)
{
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_EventDataModule_EventsDataInterface_registerEvent_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_EventDataModule_EventsDataInterface_registerEvent_name, ::Ice::Normal, context);
        ::Ice::OutputStream *ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_structRegisterEvent);
        result->endWriteParams();
        result->invoke(iceC_EventDataModule_EventsDataInterface_registerEvent_name);
    }
    catch (const ::Ice::Exception &ex)
    {
        result->abort(ex);
    }
    return result;
}

void IceProxy::EventDataModule::EventsDataInterface::end_registerEvent(const ::Ice::AsyncResultPtr &result)
{
    _end(result, iceC_EventDataModule_EventsDataInterface_registerEvent_name);
}

/// \cond INTERNAL
::IceProxy::Ice::Object *
IceProxy::EventDataModule::EventsDataInterface::_newInstance() const
{
    return new EventsDataInterface;
}
/// \endcond

const ::std::string &
IceProxy::EventDataModule::EventsDataInterface::ice_staticId()
{
    return ::EventDataModule::EventsDataInterface::ice_staticId();
}

EventDataModule::EventsDataInterface::~EventsDataInterface()
{
}

/// \cond INTERNAL
::Ice::Object *EventDataModule::upCast(EventsDataInterface *p) { return p; }

/// \endcond

namespace
{
    const ::std::string iceC_EventDataModule_EventsDataInterface_ids[2] =
        {
            "::EventDataModule::EventsDataInterface",
            "::Ice::Object"};

}

bool EventDataModule::EventsDataInterface::ice_isA(const ::std::string &s, const ::Ice::Current &) const
{
    return ::std::binary_search(iceC_EventDataModule_EventsDataInterface_ids, iceC_EventDataModule_EventsDataInterface_ids + 2, s);
}

::std::vector<::std::string>
EventDataModule::EventsDataInterface::ice_ids(const ::Ice::Current &) const
{
    return ::std::vector<::std::string>(&iceC_EventDataModule_EventsDataInterface_ids[0], &iceC_EventDataModule_EventsDataInterface_ids[2]);
}

const ::std::string &
EventDataModule::EventsDataInterface::ice_id(const ::Ice::Current &) const
{
    return ice_staticId();
}

const ::std::string &
EventDataModule::EventsDataInterface::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::EventDataModule::EventsDataInterface";
    return typeId;
#else
    return iceC_EventDataModule_EventsDataInterface_ids[0];
#endif
}

/// \cond INTERNAL
bool EventDataModule::EventsDataInterface::_iceD_registerEvent(::IceInternal::Incoming &inS, const ::Ice::Current &current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream *istr = inS.startReadParams();
    StructRegisterEvent iceP_structRegisterEvent;
    istr->read(iceP_structRegisterEvent);
    inS.endReadParams();
    this->registerEvent(iceP_structRegisterEvent, current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

namespace
{
    const ::std::string iceC_EventDataModule_EventsDataInterface_all[] =
        {
            "ice_id",
            "ice_ids",
            "ice_isA",
            "ice_ping",
            "registerEvent"};

}

/// \cond INTERNAL
bool EventDataModule::EventsDataInterface::_iceDispatch(::IceInternal::Incoming &in, const ::Ice::Current &current)
{
    ::std::pair<const ::std::string *, const ::std::string *> r = ::std::equal_range(iceC_EventDataModule_EventsDataInterface_all, iceC_EventDataModule_EventsDataInterface_all + 5, current.operation);
    if (r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch (r.first - iceC_EventDataModule_EventsDataInterface_all)
    {
    case 0:
    {
        return _iceD_ice_id(in, current);
    }
    case 1:
    {
        return _iceD_ice_ids(in, current);
    }
    case 2:
    {
        return _iceD_ice_isA(in, current);
    }
    case 3:
    {
        return _iceD_ice_ping(in, current);
    }
    case 4:
    {
        return _iceD_registerEvent(in, current);
    }
    default:
    {
        assert(false);
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }
    }
}
/// \endcond

/// \cond STREAM
void EventDataModule::EventsDataInterface::_iceWriteImpl(::Ice::OutputStream *ostr) const
{
    ostr->startSlice(ice_staticId(), -1, true);
    ::Ice::StreamWriter<EventsDataInterface, ::Ice::OutputStream>::write(ostr, *this);
    ostr->endSlice();
}

void EventDataModule::EventsDataInterface::_iceReadImpl(::Ice::InputStream *istr)
{
    istr->startSlice();
    ::Ice::StreamReader<EventsDataInterface, ::Ice::InputStream>::read(istr, *this);
    istr->endSlice();
}
/// \endcond

/// \cond INTERNAL
void EventDataModule::_icePatchObjectPtr(EventsDataInterfacePtr &handle, const ::Ice::ObjectPtr &v)
{
    handle = EventsDataInterfacePtr::dynamicCast(v);
    if (v && !handle)
    {
        IceInternal::Ex::throwUOE(EventsDataInterface::ice_staticId(), v);
    }
}
/// \endcond

namespace Ice
{
}

#endif
